name: notifications
description: Tool to publish new Universo Flutter episode
version: 0.2.1
homepage: https://universoflutter.com

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  dart_twitter_api: ^0.3.5
  firedart: ^0.8.3
  http: ^0.12.2
  spotify: ^0.5.1
  teledart: ^0.1.4
  webfeed: ^0.6.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
