name: notifications
description: Tool to publish new Universo Flutter episode
version: 0.1.0
homepage: https://universoflutter.com

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  dart_twitter_api: ^0.3.4
  http: ^0.12.2
  spotify: ^0.4.0
  teledart: ^0.1.1
  webfeed: ^0.6.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
