name: notifications
description: A simple command-line application.
version: 0.0.1
homepage: https://anchor.fm/universoflutter

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  dart_twitter_api: ^0.3.4
  http: ^0.12.2
  spotify: ^0.4.0
  teledart: ^0.0.50
  webfeed: ^0.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4
